name: Deploy to Netlify
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: |
          netlify deploy --prod --dir=dist
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_ID}}
